[WIP] Build POT against oldest-supported-numpy
PythonOT/POT pull request #349
Opened 2022-02-22 16:40 UTC by rflamary

## Types of changes

this PR is a local (branch) version of #347 that will actually run the wheel building.

## Motivation and context / Related issue

## How has this been tested (if it applies)

## PR checklist

- [ ] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [ ] The documentation is up-to-date with the changes I made (check build artifacts).
- [ ] All tests passed, and additional code has been **covered with new tests**.
- [ ] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.

2022-02-22 18:24 UTC, davidghiurco requested changes
Adding suggestions to reconcile build restrictions with `python_requires=">=3.6"` in setup.py

2022-02-22 18:24 UTC, davidghiurco commented on setup.py
>          'Programming Language :: Python :: 3.7',
```suggestion
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
```

2022-02-22 18:24 UTC, davidghiurco commented on .github/workflows/build_wheels.yml
>          CIBW_SKIP: "pp*-win* pp*-macosx* cp2* pp* cp*musl* cp36*" # remove pypy on mac and win (wrong version)
```suggestion
        CIBW_SKIP: "pp*-win* pp*-macosx* cp2* pp* cp*musl*" # remove pypy on mac and win (wrong version)
```

2022-02-23 08:53 UTC, merged

2022-02-24 16:45 UTC, davidghiurco commented
@rflamary I noticed you might want to apply the changes made in `build_wheels.yml` to `build_wheels_weekly.yml`: https://github.com/PythonOT/POT/blob/master/.github/workflows/build_wheels_weekly.yml#L42-L43

2022-02-24 16:52 UTC, davidghiurco commented
And if you do apply those changes, you might want to add to release notes that Python 3.6 support is back.

2022-02-25 14:22 UTC, rflamary commented
We are not adding python3.6 support back because python 3.6 is not supported and we should not promote old unsupported code. Actually the wheels are not builded for 3.6 because it is not supported anymore and the CI does not test 3.6. We are just allowing the user to install it even if it is not supported.

I'll update the weekly the wheels in an other PR.