[WIP] Implementation of FUGW and UCOOT
PythonOT/POT pull request #677
Opened 2024-09-18 16:10 UTC by 6Ulm

## Types of changes

This PR is dedicated to the implementation of 
1.Fused Unbalanced GW (or more correctly, its lower bound) 
2.  (Fused) Unbalanced COOT.

Since their structures, it is enough to write a common template, then write a wrapper for each divergence. 
More precisely, we create a method called `fused_unbalanced_cross_spaces_divergence` , in which
- `reg_type="independent"` corresponds to (Fused) UCOOT. This yields `unbalanced_co_optimal_transport` method.
- `reg_type="joint"` corresponds to FUGW. This yields `fused_unbalanced_gromov_wasserstein` method.

We also allow for unregularized approximation of FUGW and UCOOT, i.e. $\varepsilon = 0$, thanks to the Majorization-Minization `ot.unbalanced.mm_unbalanced` and `ot.unbalanced.lbfgsb_unbalanced` L-BFGS-B methods.

This implementation also allows for $2$ types of marginal penalization: Kullback-Leibler divergence and squared L2 norm.  We also allow the cost to be sub-differentiable w.r.t the input matrices and reference distributions. This is implemented in `unbalanced_co_optimal_transport2` and `fused_unbalanced_gromov_wasserstein` methods.

## Motivation and context / Related issue

## How has this been tested (if it applies)

## PR checklist

- [x] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] The documentation is up-to-date with the changes I made (check build artifacts).
- [x] All tests passed, and additional code has been **covered with new tests**.
- [x] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.

2024-09-28 20:18 UTC, cedricvincentcuaz requested changes
Thanks a lot @6Ulm for this impressive work.
Follows some remarks and comments to conclude the PR.
You also forgot to update `ot.gromov.__init__.py`

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/gromov/_utils.py
> +    if nx is None:
test

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/gromov/_utils.py
> +    elif divergence == "kl":
test

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/solvers.py
> +    if c is not None:
remove None test -> `arr = [M, a, b, c]`

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/utils.py
> +        return self._potentials
What's behind this change?

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/utils.py
>      def potential_a(self):
What's behind this change?

2024-09-28 20:18 UTC, cedricvincentcuaz commented on ot/utils.py
> +            return None
same

2024-10-07 14:52 UTC, 6Ulm commented on ot/gromov/_unbalanced.py
> +        return ucoot, log_ucoot
already tested in `test_ucoot.py`

2024-10-13 19:59 UTC, cedricvincentcuaz reviewed
Thank you for your last updates, you are almost there ! follows small comments on the documentation to correct then we'll be able to merge with the main branch :)

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_utils.py
> +    r"""Calculate the Bregman divergence between an arbitrary measure and a product measure.
shorter -> Fast computation of the Bregman divergence between an arbitrary measure and a product measure. Only support for Kullback-Leibler and half-squared L2 divergences.

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_utils.py
> +    .. math::
check spacing + that equation holds on a page. I think there are rendering issues.

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_utils.py
> +    r"""Calculate the Bregmain divergence between two product measures.
same comments than above

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_unbalanced.py
> +    Return the sample and feature transport plans between
merge this sentence with the first one above

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_unbalanced.py
> +    Return the sample and feature transport plans between
merge this sentence with the first one above.

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_unbalanced.py
> +    Return the unbalanced Co-Optimal Transport cost between
merge this sentence with the first one above.

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_unbalanced.py
> +    Return the transport plan between
same

2024-10-13 19:59 UTC, cedricvincentcuaz commented on ot/gromov/_unbalanced.py
> +    Return the lower bound of the fused unbalanced Gromov-Wasserstein cost between
same

2024-10-14 17:29 UTC, merged